# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - laptop-price-predictor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_40b96a620c424c16ad76ba29d2004e1b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b124ed9e22a64a968fa472fb9b6cd97a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_40b96a620c424c16ad76ba29d2004e1b }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'laptop-price-predictor'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9b83a00f9e464537a837083bccc4b606 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_40b96a620c424c16ad76ba29d2004e1b }}/appsvc/staticsite:${{ github.sha }}'